### ISSUE TITLE
Navbar Clicks are Ineffective

### ISSUE THREAD

**Issue by ayushichoudhary-19** [marshadkhn/TinDog#11]
**Description**
I have encountered that clicking on the navbar items does not navigate to the corresponding sections of the page as it should.

**To Reproduce**
1. Go to the website.
2. Click on any of the navbar items.
3. Observe that the page does not scroll down to the intended content.

**Expected Behavior**
I expected that clicking on a navbar item would smoothly scroll the page to the relevant content.

From what I understand, on clicking on 'Price', the page should scroll down smoothly to this section:
![image](https://github.com/marshadkhn/TinDog/assets/73214455/37914af1-fd17-44cc-ad3b-8879b50210eb)

Similarly for 'download' and 'contact' it should scroll down to:
![image](https://github.com/marshadkhn/TinDog/assets/73214455/b21eb279-fb8f-4703-adf2-1f6bec58de61)

 If the issue seems relevant and aligns with the goals and objectives of the project, I would like to work on it myself to enhance the website's usability.

**Comment by kubical12** [comment]
please send your pr after oct 1.😃

**Comment by ROHAN13498** [comment]
Please assign this to me .

**Comment by kubical12** [comment]
we have already assigned this issue . you can open new issues and contribute . 😀

**Comment by ROHAN13498** [comment]
Hey Thanks for the reply.I have raised my issue here take a look (Github
<https://github.com/marshadkhn/TinDog/issues/15>) Please assign the issue
to me.
