### ISSUE TITLE
Footer color is not matching

### ISSUE THREAD

**Issue by Anshul439** [marshadkhn/TinDog#111]
**Describe the bug**
Color of the footer should match with that of the navbar

**Comment by marshadkhn** [comment]
Explain your issue please

**Comment by Anshul439** [comment]
The background color in the 2nd picture is matching the navbar background color. And it's also different from that of the contact us color above it, which is looking nice.

![Screenshot 2023-10-10 102110](https://github.com/marshadkhn/TinDog/assets/123325132/b28395b2-2dea-45c0-a8d7-844ccd062f27)
![Screenshot 2023-10-10 115741](https://github.com/marshadkhn/TinDog/assets/123325132/f24f1e25-a9f5-4860-922e-0247b3b11275)

**Comment by marshadkhn** [comment]
I am working on footer someone changed the real one
