### ISSUE TITLE
[Enhancement] - Hamburger Menu Icon Does Not Transform to Close Icon on Click

### ISSUE THREAD

**Issue by ayushichoudhary-19** [marshadkhn/TinDog#12]
**Description:**
I have noticed that when clicking on the hamburger menu icon on mobile devices, it opens the navigation menu. However, there is an issue where the hamburger icon does not transform into a close icon to indicate that users can click it again to close the menu. Though it seems obvious to click on the hamburger icon again to close, it would significantly enhance the mobile user experience if the icon transformed into a close icon when the menu is open, providing clear visual feedback.

**To Reproduce:**
1. Access the website on a mobile device.
2. Click on the hamburger menu icon.
3. Observe that the menu opens, but the hamburger icon remains unchanged.

**Expected Behavior:**
I expected that when the mobile menu is opened, the hamburger icon would transform into a close icon, making it evident that clicking it again would close the menu.

**Screenshots:**
![image](https://github.com/marshadkhn/TinDog/assets/73214455/fe8a11f7-76b4-4bce-a356-51b05c371bf9)

**Additional Context:**
This enhancement would significantly improve the mobile user experience by providing clear visual feedback when interacting with the navigation menu on small screens. If the issue seems relevant, I would like to work on it myself.

**Comment by kubical12** [comment]
Hey Ayushi send your pr after oct 1 .

**Comment by ayushichoudhary-19** [comment]
@kubical12 Please review: https://github.com/marshadkhn/TinDog/pull/14
