### ISSUE TITLE
making the loginSignUp page more Attractive By adding hover effect

### ISSUE THREAD

**Issue by CoDesign-Spa27** [marshadkhn/TinDog#128]
I have Changed The Above social Media  icons and added some hover effect
https://github.com/marshadkhn/TinDog/assets/136747216/c7a4434d-626f-4fd4-a725-3c29ef0cf53e

**Comment by Ayush-Vish** [comment]
@kubical12  Please assign me this issue under hacktober fest.

**Comment by kubical12** [comment]
> @kubical12  Please assign me this issue under hacktober fest.
>   

@Ayush-Vish buddy this issue is assigned you  can open a new issue.
