### ISSUE TITLE
[BUG] : loginSignUp page is not responsive 

### ISSUE THREAD

**Issue by Ayush-Vish** [marshadkhn/TinDog#129]
**Describe the bug**
Login SignUp page is not responsive, the design is regularly available design.
![image](https://github.com/marshadkhn/TinDog/assets/127919475/7f77ae9f-8200-49f3-92aa-3f2fb5de04d0)

**To Reproduce**
1. Go to loginSignUp Page.
2. Open dev tools and see responsiveness.

**Expected behavior**
A login sign-up page should be responsive as well as the UI must be simple.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11 
 - Browser chrome
 - Version 117.0.5938.150

**Comment by Ayush-Vish** [comment]
@kubical12  Kindly assign me this issue , 
I will make a whole new loginSignUp page

**Comment by kubical12** [comment]
All the best 😃
