### ISSUE TITLE
Modifying Default Scroll Bar

### ISSUE THREAD

**Issue by Vishal-1004** [marshadkhn/TinDog#13]
It appears to me that the main color for your website is "#ff4c68" but the default scroll bar which is provided by the browser doesn't  matches well with the website.
Generally  developers for popular websites modify this default scroll bar which matches with their website's main color, since this is missing in the website so I am suggesting this modification.

##
I would really like to work on this as I have good idea of doing this in a easy and a faster way. If assigned with this task then I will definitely give you the updated version within tomorrow.

**Comment by kubical12** [comment]
Hey Vishal I really liked your idea . please send your pr after 1st oct .

**Comment by Vishal-1004** [comment]
Sure mam i will make the pull request on 1st of Oct

**Comment by kubical12** [comment]
Thats great !

**Comment by samimaktar-coder** [comment]
Can I solve this issue?

**Comment by Vishal-1004** [comment]
this issue is already solved and merged too!

**Comment by samimaktar-coder** [comment]
Where is the pull request and why this issue is still open?
