### ISSUE TITLE
Two download button for app

### ISSUE THREAD

**Issue by himanshu07gupta** [marshadkhn/TinDog#131]
**Is your feature request related to a problem? Please describe.**
There is two download button in TinDog. One  is in the upper section, and the other one is located above the 'Contact Us' section.

**Describe the solution you'd like**
I will remove lower one. Because user can find it directly on home page.

**Comment by marshadkhn** [comment]
Sure but put something interesting there
Can you do?

**Comment by himanshu07gupta** [comment]
No issue. I have two ideas for this section. Could you please suggest which one I should pursue?
1.
We can add photos of dog-related items like nutrition, clothes, food, and toys. When they make their first purchase, they will receive a free clothing set, after which they will need to pay for additional items.
2.
I can create an awareness section where I will write about precautions and guidelines for ensuring the well-being of dogs, promoting better health and a higher quality of life. This addition will make TinDog more genuine and realistic.
