### ISSUE TITLE
[BUG]-Download button and Image are Overlapping

### ISSUE THREAD

**Issue by ROHAN13498** [marshadkhn/TinDog#15]
**Describe the bug**
Download and Iphone Image is overlapping below navbar.

**To Reproduce**
1. Go to the website 
2. Right Click and press inspect
3. Decrease the size to see the ovelapping

**Expected behavior**
Overlapping shouldn't happen.

**Screenshots**

![image](https://github.com/marshadkhn/TinDog/assets/95855114/28005227-dc05-4334-966e-5214c08bfe86)

**Comment by rahulrana701** [comment]
@marshadkhn I want to work on this issue , please assign it to me under hacktoberfest 2023

**Comment by marshadkhn** [comment]
@ROHAN13498 Go ahead bro
