### ISSUE TITLE
Greetings need

### ISSUE THREAD

**Issue by CBID2** [marshadkhn/TinDog#16]
**Is your feature request related to a problem? Please describe.**
There needs to be a way to invite contributors to this project.
**Describe the solution you'd like**
Add a greeting.yml file
**Describe alternatives you've considered**

**Additional context**

**Comment by adisuyash** [comment]
Are you copying & pasting the same Issue over and over again to All repositories which are a part of hacktoberfest?

**Comment by marshadkhn** [comment]
> Are you copying & pasting the same Issue over and over again to All repositories which are a part of hacktoberfest?

Nope she is doing in my repo only
