### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by RahulGIT24** [marshadkhn/TinDog#23]
**Describe the bug**
On the home page the cards of dogs you have put are not responsive

**To Reproduce**
1. Go to  home page
2. Scroll down to "A Plan for Every Dog's Needs"
3. Now check it's responsiveness

![hack](https://github.com/marshadkhn/TinDog/assets/103873656/7ae3c00c-1793-418a-a0f0-26be57aec784)

**Expected behavior**
As the screen width reduces the cards should be in vertical order.

**Comment by RahulGIT24** [comment]
Feel free to assign this issue to me I can fix this easily

**Comment by marshadkhn** [comment]
Already open!
Issue number - #5

**Comment by RahulGIT24** [comment]
Can I fix it

**Comment by marshadkhn** [comment]
Already assigned to someone else

**Comment by RahulGIT24** [comment]
Ok then please check issue number 8 at Farm hub

**Comment by marshadkhn** [comment]
Don't comment the issue from other repo

**Comment by RahulGIT24** [comment]
Ok sorry for that
