### ISSUE TITLE
Want to make a login or sign up page for TinDog

### ISSUE THREAD

**Issue by himanshu07gupta** [marshadkhn/TinDog#25]
**Is your feature request related to a problem? Please describe.**
My feature request is related to enhancing the user experience. Specifically, I propose implementing a user registration system on TinDog to allow new users to sign up. It would be beneficial to have a dedicated login page for older users to access their accounts efficiently.

**Describe the solution you'd like**
I plan to create the necessary pages using HTML and CSS to implement the requested features. These pages will include user registration forms for new users, a dedicated login page for existing users.
The login page will include fields for basic user details, such as username and password.  The user registration page will collect necessary information from new users to create their accounts.

**Comment by marshadkhn** [comment]
Just make the UI don't do the Authentication and all

**Comment by Vivek7038** [comment]
please assign this to me , i have setup of this project on local machine

**Comment by himanshu07gupta** [comment]
@marshadkhn Thank you for assigning this task to me.
Sure, I will focus on creating the user interface (UI) for the pages using HTML and CSS
