### ISSUE TITLE
Feature request for customizable heart color in TinDog project.

### ISSUE THREAD

**Issue by farehax** [marshadkhn/TinDog#27]
I would like to request the addition of a customizable heart color in the project .Currently, the heart icon is displayed in its default color , white, and i believe to make it red ,would be a wonderful addition.
Heart color would not only add a visually appealing aspect to the project but also provide users with better user experience. Red hearts, for example, are often associated with love and positive emotions.

**Comment by marshadkhn** [comment]
Go ahead fareha

**Comment by farehax** [comment]
Thank you for considering my feature request .I believe it would be a valuable addition to the project and enhance the overall user experience.
