### ISSUE TITLE
CSS of Adoption section

### ISSUE THREAD

**Issue by fantasticbuddy** [marshadkhn/TinDog#31]
I noticed that the UI of Adoption section is not very user-attracting. I would like to update it's CSS to make it look a little good looking.

Before - 
![image](https://github.com/marshadkhn/TinDog/assets/114503561/4e633370-1f23-4456-b066-5e0348716019)

After - 
![image](https://github.com/marshadkhn/TinDog/assets/114503561/4762de3a-0649-47c6-9bdd-b7a5701636e3)

If you like this change kindly assign me this issue.
Thankyou @kubical12

**Comment by marshadkhn** [comment]
Nice riya, it's good
