### ISSUE TITLE
social media icon

### ISSUE THREAD

**Issue by himanshu07gupta** [marshadkhn/TinDog#32]
**Describe the bug**
When clicking on a icon, it fails to redirect to the intended page as expected.

**To Reproduce**
1. Go on 'TinDog'
2. Click on 'Contact Us'
3. Scroll down to the bottom
4. click on any icon
5. see error

**Expected behavior**
It should redirect to the respective page.

Solution :- I will add your official mail and  twitter handle.

**Additional context**

**Comment by marshadkhn** [comment]
Just mention the website as I don't have any social account for this

**Comment by himanshu07gupta** [comment]
> Just mention the website as I don't have any social account for this

ok sure.
