### ISSUE TITLE
Add our dogs menu option to the navbar

### ISSUE THREAD

**Issue by farehax** [marshadkhn/TinDog#37]
**Describe the solution you'd like**
I would like to propose a feature request that I believe would enhance the user experience and make TinDog even more user-friendly. I suggest adding an "Our Dogs " menu option to the menu navbar.

**Describe alternatives you've considered**
1)when a user logs into their tindog account,  they can navigate to the "Our Dogs" section from the navbar .
2) Users can browse through others users dog profiles.
3)With this feature users can also propose playdates or doggy meetups with other users dogs.

**Additional context**
![Screenshot 2023-10-01 225127](https://github.com/marshadkhn/TinDog/assets/134405736/bc6335a5-8f16-4efb-9621-b3fa3b41f258)
.

**Comment by marshadkhn** [comment]
Go ahead
