### ISSUE TITLE
Login Button Alignment Issue in Navbar

### ISSUE THREAD

**Issue by Abidsyed25** [marshadkhn/TinDog#39]
**Description**
I noticed that the login button in the navbar is not aligned properly. It appears to be misaligned to the left, causing a visual inconsistency. This issue can be observed on both desktop and mobile devices.

**Steps To Reproduce**
1. Go to TinDog website
2. Click on Hamburger icon which is on the top of the website
3. See error

**Screenshots**

![hacktoberfest](https://github.com/marshadkhn/TinDog/assets/116893970/9522e599-0954-4d73-80a6-ba61f1128cd4)

**Comment by marshadkhn** [comment]
Go ahead

**Comment by VishnuAmit** [comment]
Hey I'd like to fix the issue !
