### ISSUE TITLE
Mobile Card Alignment issue

### ISSUE THREAD

**Issue by Swarajballal** [marshadkhn/TinDog#4]
https://github.com/marshadkhn/TinDog/labels/bug
https://github.com/marshadkhn/TinDog/labels/hacktoberfest
https://github.com/marshadkhn/TinDog/labels/hacktoberfest-accepted-2023

Issue Description:
The Card component in the mobile version of the project is not displaying properly. It is expected to be responsive and adapt to variable screen sizes. However, this is not currently the case.

Expected Behavior:
The Card should resize and reformat itself to fit the screen properly, maintaining a visually appealing and functional display on all devices and screen sizes.

Steps to Reproduce:

Open the project on a mobile device or emulator.
Navigate to the section where the Card component is used.
Observe the issue where the Card does not display correctly.

Screenshots:
![image](https://github.com/marshadkhn/TinDog/assets/86348862/beb9e1d3-9ea7-44ba-8444-fc19158061a2)

I would like to take on this issue and work on fixing it.

**Comment by marshadkhn** [comment]
Don't send PR before 1 oct because it will not be accepted by hacktoberfest
