### ISSUE TITLE
Forgot Password Page

### ISSUE THREAD

**Issue by RahulGIT24** [marshadkhn/TinDog#43]
I want to create a forgot password page for your website as it was not there.

**Comment by marshadkhn** [comment]
Go buddy

**Comment by adhikari-dikshant** [comment]
Hey @RahulGIT24 well I'm Doing a different feature for the page, but it might need your help, can we collab with this in the project...??? I promise it's not something related to your work, but it might help in this project.

**Comment by RahulGIT24** [comment]
@adhikari-dikshant What's the issue number. Text me on socials I will help you

**Comment by adhikari-dikshant** [comment]
@RahulGIT24 Isuue #44 Single File.... Just above yours

**Comment by RahulGIT24** [comment]
It's not difficult you can text me on insta and twitter I will help you there.

**Comment by adhikari-dikshant** [comment]
I couldn't text you on twitter coz of that verify reasons
