### ISSUE TITLE
feat:add dark-theme in the website

### ISSUE THREAD

**Issue by samimaktar-coder** [marshadkhn/TinDog#46]
I think nowadays it is extremely important to have a dark mode on any website. I want to create the dark-theme of the website with a toggle button in the navbar.

**Comment by subhadeepbanerjee2003** [comment]
@marshadkhn where can i find the website link? please add it in readme.md of the repo

**Comment by samimaktar-coder** [comment]
I don't know why there is still an issue. Please explain me, I will try to solve this issue.
