### ISSUE TITLE
Improve the navbar and make it more beautiful.

### ISSUE THREAD

**Issue by gautamkrch** [marshadkhn/TinDog#5]
**Is your feature request related to a problem? Please describe.**
Yes, In the homepage the navbar looks a bit dull and can be made more beautiful.

**Describe the solution you'd like**
I would first love to change its increase its font size and the add change the color of the font to make it more beautiful

**Screenshot**
![Screenshot from 2023-09-26 20-24-11](https://github.com/marshadkhn/TinDog/assets/126847168/fa9deb93-6aba-4a3f-af40-0b5c7e11eb80)

**Comment by marshadkhn** [comment]
Don't send PR before 1 oct because it will not be accepted by hacktoberfest

**Comment by limFakson** [comment]
Hello can i contribute to the project.
You can actually make the nav-bar bg white, and the menu item font-size a little bit bigger

**Comment by marshadkhn** [comment]
@limFakson Assigned to @gautamkrch

**Comment by shubhampr07** [comment]
Can you assign this issue to me?

**Comment by limFakson** [comment]
i thought it has been assigned to @gautamkrch

**Comment by MehakMantri** [comment]
Can an issue be assigned to more than one contributor??

**Comment by marshadkhn** [comment]
> Can an issue be assigned to more than one contributor??
> 

Already assigned

**Comment by adityaK87** [comment]
can I pick this issue I can make it more beautiful
