### ISSUE TITLE
fix : title-image position

### ISSUE THREAD

**Issue by subhadeepbanerjee2003** [marshadkhn/TinDog#59]
**Describe the bug**
At max-width of 991px the title-image is almost touching the next section which is not looking good so we have to make fix the position .

**To Reproduce**
1. Go to the website page
2. Minimize the page to max-width of less than 991px
3. See error
4. screenshot :: **`before`** 

5.![Screenshot from 2023-10-02 20-04-05](https://github.com/marshadkhn/TinDog/assets/116381157/8e0a8ecb-0b2f-473c-bd8c-33dc1bd3add1)

**Expected behavior**
There should be a sufficient gap between upper and lower section .

**Screenshots :: `after`**
 
![Screenshot from 2023-10-02 20-04-55](https://github.com/marshadkhn/TinDog/assets/116381157/78676d19-f24a-4b62-ad99-fee8c73cc9a0)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.3 LTS
 - Browser : chrome
 - Version : 117.0.5938.132

**Comment by subhadeepbanerjee2003** [comment]
@marshadkhn

**Comment by Keshav-Aneja** [comment]
Please assign this to me

**Comment by subhadeepbanerjee2003** [comment]
@Keshav-Aneja sorry brother but already assigned to me please look for other issue
