### ISSUE TITLE
Improve the font size and decrease padding-bottom in Testimonial

### ISSUE THREAD

**Issue by Kaniz-Fatma** [marshadkhn/TinDog#6]
**Is your feature request related to a problem? Please describe.**
The font size of the testimonials are not looking that good and it somehow looks very big if we reduce the screen size.

**Describe the solution you'd like**
It will be good if we can reduce the font size and decrease the padding-bottom.

**Describe alternatives you've considered**
I am thinking about doing some work for the fonts and padding.

Screenshot of before and after changing
![Screenshot (5)](https://github.com/marshadkhn/TinDog/assets/146003237/67ee3bd0-f6d4-4009-bc30-087dff8549dc)

![Screenshot (9)](https://github.com/marshadkhn/TinDog/assets/146003237/c2721fda-0f0a-4e5e-aa9d-6aadd09f9b4b)

**Comment by marshadkhn** [comment]
Great @Kaniz-Fatma but send this PR after 1 October
