### ISSUE TITLE
 Improve Testimonial Section Responsiveness and Color Scheme

### ISSUE THREAD

**Issue by MehakMantri** [marshadkhn/TinDog#7]
Issue Description:
Problem:
The testimonial section of the website currently has issues with responsiveness, and the color scheme used across the site feels incongruous and could use improvement.

Description:
Testimonial Section Responsiveness: 
The testimonial section on the website does not adapt well to different screen sizes, making it challenging to read and navigate on mobile devices or smaller screens. It would be great to see improvements in responsiveness to ensure a consistent and user-friendly experience across various devices.

Color Scheme: 
The choice of colors used on the website, particularly in terms of contrast and readability, feels unpleasant. Some text might be difficult to read against the background, and the color palette might not convey the desired aesthetic or branding effectively. A more harmonious and visually appealing color scheme would greatly enhance the overall user experience.

screenshot:

![td](https://github.com/marshadkhn/TinDog/assets/114497437/4dc2bf9d-fd00-4550-b1ac-3880c1345f97)

**Comment by marshadkhn** [comment]
please see 
Issue number - #6
