### ISSUE TITLE
Convert than login link into btn style 

### ISSUE THREAD

**Issue by gautamkrch** [marshadkhn/TinDog#70]
**Is your feature request related to a problem? Please describe.**
I want to convert the login link into a button style

![Screenshot from 2023-10-03 13-11-05](https://github.com/marshadkhn/TinDog/assets/126847168/d31e423d-601e-4186-aa2f-2e8c9cd2b3e4)

**Comment by pragyamishra56** [comment]
Hey if it's possible then could you please assign me issue

**Comment by gautamkrch** [comment]
I have already made changes to this issues.
