### ISSUE TITLE
Request to Update Twitter Icon to X

### ISSUE THREAD

**Issue by pragyamishra56** [marshadkhn/TinDog#72]
## Feature request
I would like to request an update to the Twitter icon on the website https://tindog.co/. The current Twitter icon needs to be changed to 'X'. This update is necessary to align the website's content with the desired branding or design changes.

### Issue
![Screenshot 2023-10-03 141841](https://github.com/marshadkhn/TinDog/assets/115208912/015c6550-7fc1-4699-973f-3883a25817ee)
 
- could you please assign me i can resolve it myself

**Comment by tribhuwan-kumar** [comment]
I'll do that, can you please assign me?

**Comment by pragyamishra56** [comment]
yeah sure @tribhuwan-kumar it is assign to you

**Comment by Petsamuel** [comment]
Please assign this task to me

**Comment by pragyamishra56** [comment]
yup you can also try it

**Comment by tribhuwan-kumar** [comment]
> yup you can also try it

where is the source code of this https://tindog.co/ web?

**Comment by tribhuwan-kumar** [comment]
> yes

??

**Comment by pragyamishra56** [comment]
fork the repo

**Comment by tribhuwan-kumar** [comment]
> fork the repo

#### I did but its not the repo of that web. 
#### this is the repo of an another web
![image](https://github.com/marshadkhn/TinDog/assets/118052427/4f5bd507-4458-4809-b0a7-fa8636f41b6c)

**Comment by pragyamishra56** [comment]
this is exactly the web page where the raised issue

**Comment by pragyamishra56** [comment]
This is my first time contributing and UPDATED done #72

**Comment by pragyamishra56** [comment]
#77

**Comment by pragyamishra56** [comment]
@marshadkhn PR merged?

**Comment by marshadkhn** [comment]
Check it

**Comment by pragyamishra56** [comment]
> Check it

@marshadkhn  Kindly appreciate your merge PR Sir
