### ISSUE TITLE
TinDog logo design

### ISSUE THREAD

**Issue by farehax** [marshadkhn/TinDog#76]
- I  want to design a logo for tindog project which is based on the concept of " Tinder for dogs" i believe that compelling logo is crucial to establishing our brand identity and communicating our mission effectively. 

- I believe that a well-designed logo will be an essential part of our branding efforts and help us connect with our target audience.

- While the design of logo will be unique and subtle  . This will help users recognize the familiar concept.
![Screenshot 2023-10-03 202046](https://github.com/marshadkhn/TinDog/assets/134405736/a81fb8ea-3f5c-46bb-956d-47fe54228add)
![Screenshot 2023-10-03 201749](https://github.com/marshadkhn/TinDog/assets/134405736/0c7ec0d8-17e3-4edd-a837-d7827b7ae7ba)
![Screenshot 2023-10-03 201734](https://github.com/marshadkhn/TinDog/assets/134405736/194da551-8c9a-44d0-8d61-47f0e813cfee)

**Comment by Rahullkumr** [comment]
#76 also add the missing favicon.

I think logo designer should only do the favicon design.


![favicon](https://github.com/marshadkhn/TinDog/assets/42183055/5556f96d-f1e1-4b0b-8429-a559adb2a4ec)

**Comment by Dianesaur** [comment]
Hi, I see this is still open? Are you needed of more dog logos if so i’ll be happy to contribute?

**Comment by marshadkhn** [comment]
What's the update @farehax

**Comment by farehax** [comment]
> What's the update @farehax

done sir plz accept my pr
