### ISSUE TITLE
fix : Display property of submit button should be adjusted

### ISSUE THREAD

**Issue by subhadeepbanerjee2003** [marshadkhn/TinDog#78]
**Describe the bug**
`Display property of submit button should be changed because display:inline-block is ignored due to the float. If 'float' has a value other than 'none', the box is floated and 'display' is treated as 'block'`

**To Reproduce**
1. Go to 'css/styles.css'
2. Scroll down to 'line no - 311'
3. See error :  `screenshot of the error `

![Screenshot from 2023-10-02 20-33-17](https://github.com/marshadkhn/TinDog/assets/116381157/12af33eb-fd5b-434f-9780-6bc9237d35ca)

**Expected behavior**
the display property should be changed into `display:block`

**Screenshots**
` screenshot after changing the property value :: `

![Screenshot from 2023-10-02 21-42-11](https://github.com/marshadkhn/TinDog/assets/116381157/da77722b-565d-43d4-b519-3323efc5ca1d)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.3 LTS
 - Browser - chrome
 - Version - 117.0.5938.132

**Comment by subhadeepbanerjee2003** [comment]
@marshadkhn

**Comment by pragyamishra56** [comment]
Plz assign to me I'm working on this issue

**Comment by subhadeepbanerjee2003** [comment]
@pragyamishra56 sorry but I am  ready with the pr please look for some other issues

**Comment by pragyamishra56** [comment]
@subhadeepbanerjee2003I have almost resolved this issue. Please assign it to me. I appreciate your consideration

**Comment by subhadeepbanerjee2003** [comment]
Sorry brother but please look for other issues

**Comment by marshadkhn** [comment]
@pragyamishra56 
See this is the small program so we focus on learning and walk in order
Open issue - wait for assign - send pr

**Comment by pragyamishra56** [comment]
@marshadkhn Appreciate the guidance. Will fork the repo and submit a PR. Thank you for clarifying the status. Grateful for your help
