### ISSUE TITLE
Improve Footer Design with Vibrant Social Media Icons

### ISSUE THREAD

**Issue by MehakMantri** [marshadkhn/TinDog#8]
Problem:
The current footer design of the project could benefit from enhancements to make it more visually appealing and user-friendly. Specifically, I suggest improving the design of the footer to make it more vibrant, and responsive, and feature eye-catching social media icons, as well as enhancing the contrast for better readability.

Suggested Enhancements:

Vibrant Design:
Consider incorporating a more vibrant color scheme that aligns with the project's branding and adds visual appeal to the footer.

Responsive Design:
Implement responsive design techniques to ensure that the footer adapts gracefully to different screen sizes, including mobile devices.

Social Media Icons:
Add high-quality social media icons that are easily recognizable and link to the project's official social media profiles.

Contrast Enhancement:
Review and adjust the color choices and text formatting in the footer to ensure sufficient contrast for readability.

Screenshot:
![td1](https://github.com/marshadkhn/TinDog/assets/114497437/4d84bdca-51aa-42fe-95f1-11bccad4b670)
 I'm looking forward to collaborating on this improvement.

**Comment by marshadkhn** [comment]
Cool, go for it
Send you PR after 1 October

**Comment by parinitapatil** [comment]
May I kindly request to be assigned a task?

**Comment by MehakMantri** [comment]
I have made the desired changes but I am unable to push the code.. can you
please help me with the same
I am getting
"info: please complete authentication in your browser...
remote: Permission to marshadkhn/TinDog.git denied to MehakMantri.
fatal: unable to access 'https://github.com/marshadkhn/TinDog/': The
requested URL returned error: 403" error
this is going to be the first PR I am looking forward to raise... I will be
highly appreciate if you help me doing the same.

**Comment by marshadkhn** [comment]
Fork the repo
Create a branch
Push your code
