### ISSUE TITLE
[Bug] Error in Pricing Section Sentence - Index.html

### ISSUE THREAD

**Issue by Shiva-Sai-ssb** [marshadkhn/TinDog#83]
I noticed an error in the sentence in the pricing section of index.html.
I believe it should : 
             "Simple and affordable price plans for your dog."
I've attached a screenshot for your reference.

![Screenshot (41)](https://github.com/marshadkhn/TinDog/assets/112751524/f309448a-0d4c-445a-8bfa-18483d5b39d6)

**Comment by pragyamishra56** [comment]
@Shiva-Sai-ssb Kindly assign this issue to me. I'm eager to work on it and provide a resolution. Thank you for your consideration

**Comment by Shiva-Sai-ssb** [comment]
> @Shiva-Sai-ssb Kindly assign this issue to me. I'm eager to work on it and provide a resolution. Thank you for your consideration

Hello Mishra, I'm a fellow contributor just like you, and I've created this issue with the intention of resolving it. It's a minor issue, so feel free to take it if you'd like.

**Comment by Shiva-Sai-ssb** [comment]
> @Shiva-Sai-ssb of force, I appreciate to assigning me to this issue

I cannot assign the issue to you, but the project maintainer will review it and assign it to you.

**Comment by pragyamishra56** [comment]
@Shiva-Sai-ssb Thank You so much

**Comment by Shiva-Sai-ssb** [comment]
Hello, could you please assign the issue to @pragyamishra56? She is eager to work on it, and I have already informed her.

**Comment by pragyamishra56** [comment]
@marshadkhn  @Shiva-Sai-ssb  could you please assign me

**Comment by pragyamishra56** [comment]
@marshadkhn Sir, if @Shiva-Sai-ssb is offering me this issue, would it be possible for you to assign me this issue?

**Comment by pragyamishra56** [comment]
@marshadkhn Thank you so much, Sir. I appreciate being assigned once again
