### ISSUE TITLE
Feat: Transforming the testimonials and press section

### ISSUE THREAD

**Issue by rituraj12797** [marshadkhn/TinDog#84]
The feature is related to the problem that the testimonial section is not user friendly when it comes to buttons and color scheme
modifying it a little bit can make some good changes  

current behaviorr :  

https://github.com/marshadkhn/TinDog/assets/120770641/61bee197-4cee-46ab-9d31-f74e44378812

expected behavior:

https://github.com/marshadkhn/TinDog/assets/120770641/27859435-2fee-4cb4-bb99-44f135162a56

After modification the ui will look something like this which is more user friendly and has eye-catching effects

**Describe alternatives you've considered**

**Comment by rituraj12797** [comment]
please assign this issue to me i want to work on this issue

**Comment by pragyamishra56** [comment]
@rituraj12797 Kindly assign this issue to me. I'm eager to work on it and provide a resolution. Thank you for your consideration

**Comment by rituraj12797** [comment]
@marshadkhn please assign this issue to me i want to work on this issue
