### ISSUE TITLE
Responsive image Orientation

### ISSUE THREAD

**Issue by pragyamishra56** [marshadkhn/TinDog#88]
**Describe the bug**
an image consistently rotates in all screen sizes, including mobile, it might be considered a "persistent image rotation bug." This implies that the image does not respond appropriately to different screen sizes, and its rotation behavior is consistent across all devices, which is likely unintended. Addressing this bug would involve ensuring that the image orientation adjusts correctly based on the screen size, especially for mobile devices.

**To Reproduce**
### It should be like this
![Screenshot 2023-10-04 152642](https://github.com/marshadkhn/TinDog/assets/115208912/c20712e6-0503-4888-866c-bef6b86b3ae7)

### that's the bug 
![Screenshot 2023-10-04 152723](https://github.com/marshadkhn/TinDog/assets/115208912/cf5b366c-b2c0-4d2f-b72e-eed44fc0a284)

**Expected behavior**

**Screenshots**

**Fork this repository.**
**Clone the forked repository.**
git clone https://github.com/<your-github-username>/TinDog.git
**Navigate to the project directory.**
cd TinDog
**Create a new branch.**
git checkout -b <your_branch_name>
**Make changes.**
**Stage your changes and commit**
git add .
git commit -m "<your_commit_message>"
**Push your local commits to the remote repo.**
git push -u origin <your_branch_name>
**Create a Pull Request.**
**Congratulations! 🎉 you've made your contribution..**

**Comment by pragyamishra56** [comment]
Could you please assign me this issue I want to work on this issue

**Comment by marshadkhn** [comment]
I appreciate  your issue but that's not the bug
I did it for the sake of uniqueness

**Comment by pragyamishra56** [comment]
@marshadkhn Sir can I raise the same issue in the feature section?

**Comment by marshadkhn** [comment]
The image will be rotated coz it don't look nice straight

**Comment by pragyamishra56** [comment]
Respected Sir, I've noticed that the appearance improves when the screen size changes. May I have your permission to share the visual representation as a humble request

**Comment by pragyamishra56** [comment]
https://github.com/marshadkhn/TinDog/assets/115208912/701ca3ac-227e-4559-81b8-c036ccf17f60

## Feature 




https://github.com/marshadkhn/TinDog/assets/115208912/04bdab4c-f75d-4681-9ed5-db5a119adb71
