### ISSUE TITLE
Improve Hover Effect

### ISSUE THREAD

**Issue by fantasticbuddy** [marshadkhn/TinDog#9]
Hey @marshadkhn 
I went through the repository and found that the download buttons in intro section do not have a proper hover effect making it look very simple. I would like to add hover effect to these buttons. The hover effect will make the text bolder.

BEFORE -
![Screenshot 2023-09-28 234158](https://github.com/marshadkhn/TinDog/assets/114503561/e17bc1c3-d3f2-43be-9c8a-f45a331c9685)

AFTER -
![Screenshot 2023-09-28 234849](https://github.com/marshadkhn/TinDog/assets/114503561/8e838147-0e79-4ff7-bbe2-f2bd4b085a5d)

Please assign me this issue under hacktoberfest.
Thankyou.

**Comment by kubical12** [comment]
Please send your pr after 1st October
