### ISSUE TITLE
Responsive image Orientation

### ISSUE THREAD

**Issue by pragyamishra56** [marshadkhn/TinDog#91]
### 1. Feature Request:
I encounter frustration when the image orientation doesn't respond appropriately to different screen sizes
### 2. A solution proposal: 
I would like the image orientation to remain fixed when the webpage shrinks and rotate smoothly when flexing the image, providing a visually appealing and responsive experience
### 4. Before the feature:

https://github.com/marshadkhn/TinDog/assets/115208912/fdd9c88d-6cdb-467d-bf32-0b87e1218ada

### 5. After the feature Added:

https://github.com/marshadkhn/TinDog/assets/115208912/0fa98680-4700-42d9-b947-f71227532e4e

**Comment by marshadkhn** [comment]
Oh you're talking about this
Got it

**Comment by pragyamishra56** [comment]
Thankyou for assigning me @marshadkhn 
I have sent you a Twitter invite. Is it okay if we connect? You are the best mentor I have ever had and I would like to contribute Sir

**Comment by marshadkhn** [comment]
Sure would to connect and have a healthy conversation
