### ISSUE TITLE
hover effect for send message button

### ISSUE THREAD

**Issue by farehax** [marshadkhn/TinDog#93]
I have a feature request that i believe could enhance the user interface and overall user experience on tindog . I'd like to suggest the implementation of a hover effect on the send button within the messaging feature .currently the button appears static and adding a hover effect would not only make the UI more interactive but also provide visual feedback to users when they hover their mouse pointer over it.

**Comment by marshadkhn** [comment]
Ig the current contact us page looks good
You may apply the hover effect

**Comment by ankushbhardwaj408** [comment]
Hi @marshadkhn i would like to work on this. Please assign it to me.

**Comment by farehax** [comment]
okay @marshadkhn  will do this plz assign me

**Comment by marshadkhn** [comment]
Change the title and description

**Comment by Ayush-Vish** [comment]
I would like to work on this issue if this pull request is not closed.
