### ISSUE TITLE
Enhancement: Optimize Logo Placement to Prevent Displacement on Interaction

### ISSUE THREAD

**Issue by ankushbhardwaj408** [marshadkhn/TinDog#94]
**Is your feature request related to a problem? Please describe.**
In this web application, i faced an issue where logos were displaced slightly when users interacted with them.

**Describe the solution you'd like**
Logos should be optimized to prevent any displacement or movement when users interact with them. Whether users hover over the logos or click on them, there should be no visible shift in the logo positions. The logos should remain stable and maintain their layout integrity.

Actual Behavior

https://github.com/marshadkhn/TinDog/assets/93874580/aa97ffba-6ca9-4e52-b81a-2e5f3a26d184

Expected Behavior

https://github.com/marshadkhn/TinDog/assets/93874580/c765b8a6-3097-4648-9c18-5f60b556a8a5

**Describe alternatives you've considered**

**Additional context**

**Comment by marshadkhn** [comment]
It looks good i guess when anyone hover

**Comment by ankushbhardwaj408** [comment]
But when we hover over any of them the other logos get displaced

**Comment by ankushbhardwaj408** [comment]
Hi @marshadkhn I am new to open source and eager to contribute. Please tell me some issues or any suggestions from your side.

**Comment by marshadkhn** [comment]
DM me on twitter 
Username - marshadkhn
