### ISSUE TITLE
Smooth Hover Effect 

### ISSUE THREAD

**Issue by aj12-houdini** [marshadkhn/TinDog#99]
### Feature Request
I would like to add a feature that smoothens the effect when hovering over the buttons on the website. 

### Current Issue
Right now when I hover there is a sudden jitter that doesn't look good to the eye.

**Comment by marshadkhn** [comment]
Can you propose a video

**Comment by marshadkhn** [comment]
I guess the buttons are good on hover
If the only button that looks odd is of send messge and on that @farehax with Issue number - #93
Still you have better idea propose a video

**Comment by pragyamishra56** [comment]
@marshadkhn Sir I've already added the feature

**Comment by aj12-houdini** [comment]
I was thinking something like this 


https://github.com/marshadkhn/TinDog/assets/97756925/406205e0-f144-4b33-9b08-6a179525d09e

**Comment by marshadkhn** [comment]
Enhancement is already done, thanks for your contribution
